/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadastroLaudoForm.java
 *
 * Created on 27/01/2012, 09:20:34
 */
package br.ufmg.hc.telessaude.diagnostico.gestao.forms;

import br.ufmg.hc.telessaude.diagnostico.dominio.commons.Acao;
import br.ufmg.hc.telessaude.diagnostico.dominio.commons.Mensagens;
import br.ufmg.hc.telessaude.diagnostico.dominio.entity.ConteudoExame;
import br.ufmg.hc.telessaude.diagnostico.dominio.entity.Exame;
import br.ufmg.hc.telessaude.diagnostico.dominio.entity.HistoricoClinico;
import br.ufmg.hc.telessaude.diagnostico.dominio.entity.Laudo;
import br.ufmg.hc.telessaude.telediagnostico.xmlfactory.estrutura.LAUDO;
import br.ufmg.hc.telessaude.telediagnostico.xmlfactory.gerador.XMLFactory;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.*;

/**
 *
 * @author paulo.gomes
 */
public class ConteudoLaudoForm extends Form {

    private Laudo laudo;

    private final LaudoForm form;

    /**
     * Creates new form CadastroLaudoForm
     *
     * @param desktop
     * @param laudo
     * @param acao
     * @param form
     * @param observable
     */
    public ConteudoLaudoForm(final JDesktopPane desktop, final Laudo laudo, final Acao acao, final LaudoForm form) {
        super(desktop, acao);
        initComponents();

        desktop.add(this);
        this.form = form;
        this.laudo = laudo;

        carregarMenu();

        this.txtLaudo.setFont(new Font("Tahoma", Font.PLAIN, 14));
        if (laudo.getConteudo() != null) {
            XMLFactory<LAUDO> laudoFactory = new XMLFactory<>();
            LAUDO ld = laudoFactory.gerarEstrutura(laudo.getConteudo(), "UTF-8");
            this.txtLaudo.setText(ld.getCONTEUDO());
        }
    }

    private void carregarLaudo() {

    }

    private void carregarMenu() {

    }

    public void cancelarForm() {
        if (exibirConfirmacao(Mensagens.CONFIRMAR_CANCELAR) == JOptionPane.YES_OPTION) {
            prepararExameParaEnvio();
            List<Exame> exames = new ArrayList<>();
            exames.add(laudo.getExame());
            form.fecharJanela();
        }
    }

    private void prepararExameParaEnvio() {
        if (laudo != null) {
            List<ConteudoExame> conteudos = new ArrayList();
            for (ConteudoExame conteudoExame : laudo.getExame().getConteudosExames()) {
                conteudos.add(new ConteudoExame(conteudoExame.getId()));
            }
            laudo.getExame().setConteudosExames(conteudos);
            List<HistoricoClinico> historicos = new ArrayList();
            for (HistoricoClinico historico : laudo.getExame().getHistoricosClinicos()) {
                historicos.add(new HistoricoClinico(historico.getId()));
            }
            laudo.getExame().setHistoricosClinicos(historicos);
            laudo.getExame().setPaciente(null);
            laudo.getExame().setPontoRemoto(null);
            laudo.getExame().setPrioridade(null);
            laudo.getExame().setStatus(null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popFrases = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLaudo = new javax.swing.JTextPane();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Laudo");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufmg/hc/telessaude/diagnostico/gestao/images/telessaude1.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(590, 504));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Laudo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 255)));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufmg/hc/telessaude/diagnostico/gestao/images/close.png"))); // NOI18N
        btnCancelar.setMnemonic(KeyEvent.VK_C);
        btnCancelar.setText("Fechar");
        btnCancelar.setToolTipText("Fechar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtLaudo.setEditable(false);
        txtLaudo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLaudo.setComponentPopupMenu(popFrases);
        txtLaudo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtLaudoMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(txtLaudo);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCancelar)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 4, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cancelarForm();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
//        ecg12Controller.FecharExame();
    }//GEN-LAST:event_formInternalFrameClosing

    private void txtLaudoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLaudoMousePressed
        ////////////////////////////////////////////////////////////////////////////////       
    }//GEN-LAST:event_txtLaudoMousePressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu popFrases;
    private javax.swing.JTextPane txtLaudo;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @return
     */
    private long getIntervalInSeconds() {
        Calendar latenciaInicial = Calendar.getInstance();
        Calendar latenciaFinal = Calendar.getInstance();
        return ((latenciaFinal.getTimeInMillis() - latenciaInicial.getTimeInMillis()) / 1000);
    }

    @Override
    public void execute(Acao acao) {
        switch (acao) {
            case ATUALIZAR:
                carregarMenu();
                break;
        }
    }

    @Override
    public void dispose() {
        laudo = null;
        super.dispose();
    }
}
