/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadastroLaudoForm.java
 *
 * Created on 27/01/2012, 09:20:34
 */
package br.ufmg.hc.telessaude.diagnostico.gestao.forms;

import br.ufmg.hc.telessaude.diagnostico.dominio.commons.Acao;
import br.ufmg.hc.telessaude.diagnostico.dominio.commons.Mensagens;
import br.ufmg.hc.telessaude.diagnostico.dominio.dao.EcgAnalysDAOImpl;
import br.ufmg.hc.telessaude.diagnostico.dominio.entity.Laudo;
import br.ufmg.hc.telessaude.diagnostico.dominio.exceptions.DAOException;
import br.ufmg.hc.telessaude.diagnostico.dominio.glasgow.EcgAnalys;
import br.ufmg.hc.telessaude.diagnostico.dominio.glasgow.ReportEcgAnalys;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author paulo.gomes
 */
public class GlasgowForm extends Form {

    private Laudo laudo;

    private final LaudoForm form;

    /**
     * Creates new form CadastroLaudoForm
     *
     * @param desktop
     * @param laudo
     * @param acao
     * @param form
     * @param observable
     */
    public GlasgowForm(final JDesktopPane desktop, final LaudoForm form) {
        super(desktop, Acao.NULA);
        initComponents();

        desktop.add(this);
        this.form = form;
        this.laudo = form.laudo;
        String texto = form.referencia.exibirConteudo();
        if (texto != null) {
            txtLaudo.setText(texto);
        }
    }

    public void cancelarForm() {
        if (exibirConfirmacao(Mensagens.CONFIRMAR_CANCELAR) == JOptionPane.YES_OPTION) {
            form.fecharJanela();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popFrases = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLaudo = new javax.swing.JTextPane();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Glasgow");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufmg/hc/telessaude/diagnostico/gestao/images/telessaude1.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(590, 504));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Conteudo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 255)));

        txtLaudo.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtLaudo.setComponentPopupMenu(popFrases);
        txtLaudo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtLaudoMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(txtLaudo);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
//        ecg12Controller.FecharExame();
    }//GEN-LAST:event_formInternalFrameClosing

    private void txtLaudoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLaudoMousePressed
        ////////////////////////////////////////////////////////////////////////////////       
    }//GEN-LAST:event_txtLaudoMousePressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu popFrases;
    private javax.swing.JTextPane txtLaudo;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @return
     */
    private long getIntervalInSeconds() {
        Calendar latenciaInicial = Calendar.getInstance();
        Calendar latenciaFinal = Calendar.getInstance();
        return ((latenciaFinal.getTimeInMillis() - latenciaInicial.getTimeInMillis()) / 1000);
    }

    @Override
    public void execute(Acao acao) {
        switch (acao) {
            case ATUALIZAR:
                break;
        }
    }

    @Override
    public void dispose() {
        laudo = null;
        super.dispose();
    }
}
