/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufmg.hc.telessaude.diagnostico.gestao.forms;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.io.File;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;

/**
 *
 * @author breno.melo
 */
public class ImagemTeste extends javax.swing.JFrame {

    JPanel p;
    Point pPoint;
    MouseEvent pressed;

    /**
     * Creates new form ImagemTeste
     *
     * @param imagemFundo
     * @param imagemFrente
     */
    public ImagemTeste(File imagemFundo, File imagemFrente) {
        initComponents();
        DisplayPanel dis = new DisplayPanel(imagemFundo, false);
        DisplayPanel dis2 = new DisplayPanel(imagemFrente, true);
        dis2.setBackground(new Color(0, 0, 0, 5));
        dis.setBackground(new Color(0, 0, 0, 5));
        painelTeste.setVisible(false);
        dis.setOpaque(false);
        dis2.setOpaque(false);
        this.add(dis2);
        this.add(painelTeste);
        this.add(dis);

    }

    private void redimencionar(JPanel panel) {
        Dimension size = Toolkit.getDefaultToolkit().getScreenSize();
        panel.setSize(size);
        panel.setLocation(0, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTeste = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout painelTesteLayout = new javax.swing.GroupLayout(painelTeste);
        painelTeste.setLayout(painelTesteLayout);
        painelTesteLayout.setHorizontalGroup(
            painelTesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );
        painelTesteLayout.setVerticalGroup(
            painelTesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(painelTeste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelTeste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel painelTeste;
    // End of variables declaration//GEN-END:variables

    public void movimentar(final JPanel p) {
        p.setSize(900, 600);

        p.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                if (e.getSource() == p) {
                    pressed = e;
                }
            }
        });

        p.addMouseMotionListener(new MouseMotionAdapter() {
            public void mouseDragged(MouseEvent e) {
                if (e.getSource() == p) {
                    pPoint = p.getLocation(pPoint);
                    int x = pPoint.x - pressed.getX() + e.getX();
                    int y = pPoint.y - pressed.getY() + e.getY();
                    p.setLocation(x, y);
                }
            }
        });

        p.setBorder(new LineBorder(Color.black));

        JPanel mainPanel = new JPanel();
        mainPanel.add(p);

        JPanel mainPanel2 = new JPanel();
        mainPanel2.add(new JLabel("TEst"));

        getContentPane().add("Center", mainPanel);
        getContentPane().add("East", mainPanel2);
        setSize(900, 600);
        setVisible(true);
    }

}


//}
